#!/usr/local/bin/node
const smc = require('smc');
 
let data = {}
Object.keys(smc.metrics).forEach(function(key) {
  const value = smc.get(key);
  if (value > 0) {
    data[key] = value;
  }
  data.FAN0 = smc.fanRpm(0);
  data.FAN1 = smc.fanRpm(1);
});
console.log(JSON.stringify(data));